modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://gitlab.com/jomcraft-sources/invsync/-/issues"

[[mods]]
modId="invsync"
version="${version}"
displayName="InvSync"
displayURL="https://www.curseforge.com/minecraft/mc-mods/invsync"
credits="Credits go the the Jomcraft Network development team"
authors="Jomcraft Network"
description='''
With this mod you can sync your inventory and the tablist between different servers. That means if you leave one server and join to another server, your inventory will be the same. Also you can see which players are active on another linked server without even visiting it.
'''

[[dependencies.invsync]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.invsync]]
    modId="jclib"
    mandatory=true
    versionRange="[1.1.0,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.invsync]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"