modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="invsync"
version="${version}"
displayName="InvSync"
updateJSONURL="http://myurl.me/"
displayURL="http://example.com/"
credits="Thanks for this example mod goes to Java"
authors="Love, Cheese and small house plants"
description='''
Lorem ipsum dolor sit amet
'''

[[dependencies.invsync]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.invsync]]
    modId="jclib"
    mandatory=true
    versionRange="[1.0.1,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.invsync]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"